config-path = /Users/bhanumamillapalli/Desktop/Current_Work/2024_Research_Project/Models/arr/config_files/config_hpopt.toml
target-columns = [A]
smiles-columns = [smiles]
accelerator = cpu
data-path = /Users/bhanumamillapalli/Desktop/Current_Work/2024_Research_Project/Datasets/Viscosity_Data/chemprop/arr_dataset.csv
output-dir = /Users/bhanumamillapalli/Desktop/Current_Work/2024_Research_Project/Models/arr
task-type = regression
epochs = 200
num-workers = 0
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
activation = RELU
aggregation = mean
aggregation-norm = 100
ffn-num-layers = 1
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08
warmup-epochs = 2
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
batch-size = 64
message-hidden-dim = 300
depth = 3
dropout = 0.0
ffn-hidden-dim = 300
init-lr = 0.0001
max-lr = 0.001
final-lr = 0.0001
raytune-num-samples = 50
hyperopt-n-initial-points = 20
raytune-grace-period = 50