# PATH Variables
config-path = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Config_Files/config_transfer.toml
data-path = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Datasets/vapour_pressure_data.csv
output-dir = /home/bhanu/Documents/Chemprop_Models/
model-frzn = /home/bhanu/Documents/Chemprop_Models/Best_Models/viscosity/best.pt


# Hyperparameters
activation = ELU
aggregation = sum
aggregation-norm = 59
ffn-num-layers = 2
warmup-epochs = 8
batch-size = 128
message-hidden-dim = 2300
depth = 2
dropout = 0.0
ffn-hidden-dim = 500
init-lr = 0.00001632
max-lr = 0.00042856
final-lr = 0.000005124
epochs = 500
frzn-ffn-layers = 0

# GPU/CPU and other training stuff
accelerator = gpu
num-workers = 7
devices = auto
ensemble-size = 1



# Don't Change
target-columns = [vapor_pressure]
smiles-columns = [smiles]
splits-column = splits
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
task-type = regression
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08


