# PATH Variables
config-path = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Config_Files/config_cond.toml
data-path = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Datasets/cond_data.csv
output-dir = /home/bhanu/Documents/Chemprop_Models/

# Hyperparameters
activation = LEAKYRELU
aggregation = norm
aggregation-norm = 183
ffn-num-layers = 2
warmup-epochs = 15
batch-size = 32
message-hidden-dim = 300
depth = 4
dropout = 0.35
ffn-hidden-dim = 400
init-lr = 0.0000364560593
max-lr = 0.000368055
final-lr = 0.000003400362
loss_reg = 0.1
epochs = 500


# GPU/CPU and other training stuff
accelerator = gpu
num-workers = 7
devices = auto
ensemble-size = 1



# Don't Change
target-columns = [Conductivity]
smiles-columns = [smiles]
splits-column = splits
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
task-type = regression
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08


