# PATH Variables
config-path = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Config_Files/config_arr.toml
data-path = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Datasets/viscosity_arr_data.csv
output-dir = /home/bhanu/Documents/Chemprop_Models/

# Hyperparameters
activation = SELU
aggregation = mean
aggregation-norm = 64
ffn-num-layers = 1
warmup-epochs = 22
batch-size = 32
message-hidden-dim = 2400
depth = 4
dropout = 0.0
ffn-hidden-dim = 600
init-lr = 0.00010287
max-lr = 0.0010235
final-lr = 0.0000230707
epochs = 500

# GPU/CPU and other training stuff
accelerator = gpu
num-workers = 7
devices = auto
ensemble-size = 1



# Don't Change
target-columns = [Viscosity]
smiles-columns = [smiles]
splits-column = splits
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
task-type = regression
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08


