# PATH Variables
config-path = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Config_Files/config.toml
data-path = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Datasets/cond_data_debug.csv
output-dir = /home/bhanu/Documents/Chemprop_Models/

# Hyperparameters
activation = RELU
aggregation = mean
aggregation-norm = 100
ffn-num-layers = 1
warmup-epochs = 1
batch-size = 64
message-hidden-dim = 300
depth = 3
dropout = 0.0
ffn-hidden-dim = 300
init-lr = 0.0001
max-lr = 0.001
final-lr = 0.0001
epochs = 5

# GPU/CPU and other training stuff
accelerator = gpu
num-workers = 7
devices = auto
ensemble-size = 1



# Don't Change
target-columns = [Conductivity]
smiles-columns = [smiles]
splits-column = splits
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
task-type = regression
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08


