# PATH Variables
config-path = /Users/bhanumamillapalli/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Config_Files/config_mac.toml
data-path = /Users/bhanumamillapalli/Documents/GitHub/chemprop/tests/data/regression/mol/mol.csv
output-dir = /Users/bhanumamillapalli/Documents/Chemprop_Models/

# Hyperparameters
activation = RELU
aggregation = mean
aggregation-norm = 100
ffn-num-layers = 1
warmup-epochs = 20
batch-size = 64
message-hidden-dim = 300
depth = 3
dropout = 0.4
ffn-hidden-dim = 300
init-lr = 0.0001
max-lr = 0.001
final-lr = 0.0001
epochs = 500

# GPU/CPU and other training stuff
accelerator = cpu
num-workers = 0
devices = auto
ensemble-size = 1



# Don't Change
target-columns = [lipo]
smiles-columns = [smiles]
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
task-type = regression
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08


