# PATH Variables
config-path = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Config_Files/config_hpopt.toml
data-path = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Datasets/viscosity_data.csv
output-dir = /home/bhanu/Documents/Chemprop_Models/

#hpopt stuff
raytune-num-samples = 50
hyperopt-n-initial-points = 25
hpopt-save-dir = /home/bhanu/Documents/Chemprop_Models/hpopt
search-parameter-keywords = basic

# Hyperparameters
activation = RELU
aggregation = mean
aggregation-norm = 100
ffn-num-layers = 3
warmup-epochs = 2
batch-size = 64
message-hidden-dim = 300
depth = 3
dropout = 0.5
ffn-hidden-dim = 300
init-lr = 0.0001
max-lr = 0.001
final-lr = 0.0001
epochs = 50

# GPU/CPU and other training stuff
accelerator = cuda
num-workers = 4
devices = auto
ensemble-size = 1
raytune-num-workers = 1
raytune-use-gpu = False


# Don't Change
target-columns = [Viscosity]
smiles-columns = [smiles]
splits-column = splits
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
task-type = regression
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08


