# PATH Variables
config-path = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Config_Files/config_transfer.toml
data-path = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Report/Data/cond/cond_0.1.csv
output-dir = /home/bhanu/Documents/Chemprop_Models/
model-frzn = /home/bhanu/Documents/GitHub/Thermal_Fluid_Prediction_GNN/Barlow_Twins/BT_big.ckpt


# Hyperparameters
activation = leakyrelu
aggregation = mean
aggregation-norm = 100
ffn-num-layers = 1
warmup-epochs = 2
batch-size = 64
message-hidden-dim = 700
depth = 3
dropout = 0.3
ffn-hidden-dim = 1000
init-lr = 0.0001
max-lr = 0.001
final-lr = 0.0001
epochs = 100
loss_reg = 0.15

# GPU/CPU and other training stuff
accelerator = gpu
num-workers = 7
devices = auto
ensemble-size = 1



# Don't Change
target-columns = [target]
smiles-columns = [smiles]
splits-column = splits
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-folds = 1
data-seed = 0
task-type = regression
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08


